### ISSUE TITLE
Weapon not blackisting

### ISSUE THREAD

**Issue by yashj131** [TFNRP/dynamicblacklist#7]
Hello, i tried to use the weapon blacklislt but for some reason its not working
[config.zip](https://github.com/TFNRP/dynamicblacklist/files/9816993/config.zip)

**Comment by yashj131** [comment]
Got it to work. Sorry

But it has to be restarted everytime foe it to blacklist the weapons. Any solutions?

**Comment by MrGriefs** [comment]
This issue already exists #6
